[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "semester_project_subliminal_learning"
authors = [
    # TODO configure authors
    # { name = "Jane Smith", email = "jane.smith@example.com" },
    # { name = "John Doe", email = "john.doe@example.com" },
]
description = ""
readme = "README.md"
requires-python = "~=3.12.0"
dependencies = [
    "jaxtyping>=0.3.9",
    "datasets>=4.7.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "optuna>=4.7.0",
    "pandas>=3.0.1",
    "pytorch-cka>=1.0.1",
    "torch>=2.10.0",
    "torch-cka>=0.21",
    "torchvision>=0.25.0",
    "tqdm>=4.67.3",
    "transformers>=5.3.0",
]
dynamic = ["version"]

[dependency-groups]
dev = [
    "beartype>=0.22.9",
    "notebook~=7.5",
    "pre-commit~=4.5",
    "pytest~=9.0",
    "ruff==0.15.0",
]

[tool.setuptools.dynamic]
version = {attr = "semester_project_subliminal_learning.__version__"}

[tool.ruff]
target-version = "py312"
line-length = 88

[tool.ruff.lint]
extend-select = ["I"]
ignore = ["F722"]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
